name: Deploy

on:
  push:
    branches: 
      - main
    paths:
      - 'src/Extensibility.*/**'
      - 'bicep-extensibility.sln'
  workflow_dispatch:

env:
  rgName: bicep-extensibility-svc
  baseName: bicepextsvc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.1

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: |
          dotnet publish \
            --configuration Release \
            --output ./deploy/package \
            ./src/Extensibility.Host

      - name: Generate Zip
        run: |
          pushd ./deploy/package
          zip -r ../package.zip .
          popd

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        run: |
          az deployment group create \
            --resource-group ${{ env.rgName }} \
            --name ${{ github.run_number }} \
            --template-file ./deploy/main.bicep \
            --parameters \
              baseName=${{ env.baseName }}

          az functionapp deployment source config-zip \
            --resource-group ${{ env.rgName }} \
            --name ${{ env.baseName }} \
            --src ./deploy/package.zip