name: Test minikube

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:

    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master

    # now you can run kubectl to see the pods in the cluster
    - name: kubectl
      run: kubectl get pods -A

    - name: cat kubeconfig
      run: cat ~/.kube/config

    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2

    - name: Build
      run: dotnet build src/MiniKubeTests/MiniKubeTests.csproj --configuration release

    - name: Test
      run: dotnet test src/MiniKubeTests/MiniKubeTests.csproj --configuration release --logger "console;verbosity=detailed"